import {
  AlarmClock,
  AlertTriangle,
  ArrowLeft,
  Bell,
  BellPlus,
  BellRing,
  Blocks,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  LayoutList,
  CheckCircle,
  ChevronRight,
  Circle,
  Clock,
  Download,
  Eye,
  File,
  Flag,
  Layers,
  LayoutGrid,
  List,
  ListTodo,
  Loader2,
  LogOut,
  Mail,
  Maximize2,
  MessageCircle,
  Monitor,
  Moon,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Power,
  Reply,
  Repeat,
  RotateCcw,
  Search,
  SearchX,
  Send,
  Settings,
  Share2,
  Shield,
  Smartphone,
  Sparkles,
  Sun,
  Tag,
  Trash2,
  UserPlus,
  Users,
  Volume2,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Mapa kebab → componente lucide (os nomes batem com os do protótipo). */
const MAP: Record<string, LucideIcon> = {
  'alarm-clock': AlarmClock,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  bell: Bell,
  'bell-plus': BellPlus,
  'bell-ring': BellRing,
  blocks: Blocks,
  calendar: CalendarDays,
  'calendar-clock': CalendarClock,
  camera: Camera,
  check: Check,
  'layout-list': LayoutList,
  'check-circle': CheckCircle,
  'chevron-right': ChevronRight,
  circle: Circle,
  clock: Clock,
  download: Download,
  eye: Eye,
  file: File,
  flag: Flag,
  layers: Layers,
  'layout-grid': LayoutGrid,
  list: List,
  'list-todo': ListTodo,
  'loader-2': Loader2,
  'log-out': LogOut,
  mail: Mail,
  'maximize-2': Maximize2,
  'message-circle': MessageCircle,
  monitor: Monitor,
  moon: Moon,
  paperclip: Paperclip,
  pencil: Pencil,
  pin: Pin,
  plus: Plus,
  power: Power,
  reply: Reply,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  search: Search,
  'search-x': SearchX,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sun: Sun,
  tag: Tag,
  'trash-2': Trash2,
  'user-plus': UserPlus,
  users: Users,
  'volume-2': Volume2,
  x: X,
  zap: Zap,
}

interface IconProps {
  name: keyof typeof MAP | string
  size?: number
  className?: string
  style?: React.CSSProperties
  strokeWidth?: number
}

export function Icon({ name, size = 16, className, style, strokeWidth = 2 }: IconProps) {
  const Cmp = MAP[name] ?? Circle
  return <Cmp size={size} className={className} style={style} strokeWidth={strokeWidth} />
}
